name: Bug Report
description: Report a reproducible defect in Jig behavior.
title: "bug: "
labels:
  - bug
body:
  - type: dropdown
    id: failure_surface
    attributes:
      label: Failure Surface
      options:
        - startup
        - cmdline
        - completion
        - lsp
        - ui
        - performance
        - platform
        - integration
        - agent
        - security
    validations:
      required: true
  - type: input
    id: nvim_version
    attributes:
      label: Neovim version
      placeholder: "nvim --version (first line)"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "e.g. Ubuntu 24.04, macOS 15, Windows 11, WSL Ubuntu"
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: Terminal
      placeholder: "e.g. Kitty, WezTerm, iTerm2, Windows Terminal"
    validations:
      required: true
  - type: input
    id: shell
    attributes:
      label: Shell
      placeholder: "e.g. bash, zsh, fish, pwsh"
    validations:
      required: true
  - type: input
    id: nvim_appname
    attributes:
      label: NVIM_APPNAME
      placeholder: "jig, jig-safe, or custom value"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide exact commands and steps.
    validations:
      required: true
  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual
    validations:
      required: true
  - type: checkboxes
    id: triage_checks
    attributes:
      label: Triage checks completed
      options:
        - label: reproduced in jig-safe
          required: true
        - label: ran :checkhealth jig
          required: true
        - label: attached :JigHealth output (or stated why unavailable)
          required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Attach logs, traces, screenshots, CI links.
    validations:
      required: true
