name: Feature Request
description: Propose a feature with verification and rollback path.
title: "feat: "
labels:
  - enhancement
body:
  - type: input
    id: problem
    attributes:
      label: Problem to Solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Behavior
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: true
  - type: textarea
    id: verification
    attributes:
      label: Verification Plan
      description: Include deterministic commands and expected outputs.
    validations:
      required: true
  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
      description: How to disable/revert safely.
    validations:
      required: true
